all:
	g++ -O3 main.cpp -o main
	./main $(f)

compile:
	g++ -O3 main.cpp -o main
run:
	./main $(f)
onlyOne:
	g++ -O3 onlyone.cpp -o onlyone
	./onlyone $(f) $(seed)
onlyOneCompile:
	g++ -O3 onlyone.cpp -o onlyone
onlyOneRun:
	./onlyone $(f) $(seed)

